version: '2'
services:
  namenode:
    image: honeyshawn/hadoop:bug
    container_name: namenode
    hostname: namenode
    ports:
        - "50070:50070"  # namenode url
        - "49707:49707"
        - "19888:19888"  # jobhistory url
        - "10020:10020"  # jobhistory
        - "9000:9000"    # namenode
    env_file:
      - "./hadoop.env"
    depends_on:
      - resource-manager
      - secondary

  resource-manager:
    image: honeyshawn/hadoop:bug
    hostname: resource-manager
    container_name: resource-manager
    ports:
      - "8088:8088"  # yarn url
    env_file:
      - "./hadoop.env"

  secondary:
    image: honeyshawn/hadoop:bug
    container_name: secondary
    hostname: secondary
    ports:
      - "50090:50090"  # SecondaryNameNode url
    env_file:
      - "./hadoop.env"

